### PR TITLE
Implemented full timer feature and cleared most checkstyle in question view files

### PR DESCRIPTION
**Pull request by SazzGuy**

### CODE REVIEW

**Comment by SazzGuy** [comment]
there are some conflicts mainly due to the new animals added (since i created my branch before it) that we need to resolve

**Review by bem-boi — APPROVED** [review]
awesome pr. timer now works!!

**Review by jerryq0101 — APPROVED** [review]
smurfed

**Review by ZekeWeng — APPROVED** [review]
great work!

**Comment by SazzGuy** [comment]
nice optimizing of only creating new timer when there is a new question, Jerry!

**Pull request merged**
