### PR TITLE
added QuestionView

### PR DESCRIPTION
**Pull request by xStylistic**
just the base

### CODE REVIEW

**Comment by bem-boi** [comment]
looks good

**Review by bem-boi — APPROVED** [review]
good pr

**Review by SazzGuy — COMMENTED** [review]
fine as a base but noting that it will need a lot of rework

**Review by SazzGuy — APPROVED** [review]

**Review by ZekeWeng — APPROVED** [review]
Great visuals, clean code!

**Review by jerryq0101 — APPROVED** [review]
LFG!

**Pull request merged**
