### PR TITLE
implemented the main use case of answering questions in a game by..

### PR DESCRIPTION
**Pull request by SazzGuy**
updating the game DAI, input/output boundary, controller, state, view model and adding new game and questionAnswer entities. The view files are just sample to help in coding, no need to merge it

### CODE REVIEW

**Review by jerryq0101 — APPROVED** [review]
Good pr

**Comment by bem-boi** [comment]
great pr!!!!!!

**Review by ZekeWeng — APPROVED** [review]
Looks good. Maybe review checkstyle after.

**Review by bem-boi — APPROVED** [review]
amazing pr!

**Review by xStylistic — APPROVED** [review]
great work

**Pull request merged**
