### PR TITLE
added total time elapsed feature and displaying current question index

### PR DESCRIPTION
**Pull request by SazzGuy**

### CODE REVIEW

**Review by ZekeWeng — CHANGES_REQUESTED** [review]
Great work! There are some merge conflicts that need resolving but looks great. Thanks for moving instance variables higher up to entities, allowing us to adhere to Clean Architecture.

**Comment by jerryq0101** [comment]
Good call deleting and modifying the initially useless getters.

Checkstyle looks better now that useless dependencies are removed.

Good abstraction of dependencies by putting the timer logic in gamestateinteractor.

**Review by xStylistic — APPROVED** [review]
time elapsed finally done yay. good fixes of checkstyle, nice getter functions added to abstract main. this is good for maintaining encapsulation

**Review by bem-boi — APPROVED** [review]
Thanks for adding the timer saswata! good PR. however, you could make gettotaltime more efficient by using getsecondselasped().

**Comment by SazzGuy** [comment]
sorry i accidentally removed the initialization of difficulty in abstract game. Whoever does the next commit please add it thank you

**Pull request merged**
