### PR TITLE
created the endscreen and the questionwrong view frames

### PR DESCRIPTION
**Pull request by bem-boi**
created the endscreen and the questionwrong view frames.

### CODE REVIEW

**Comment by jerryq0101** [comment]
noice pr

**Review by jerryq0101 — APPROVED** [review]
Good PR. Reviewed

**Comment by ZekeWeng** [comment]
Looks Good!

**Review by ZekeWeng — APPROVED** [review]

**Comment by xStylistic** [comment]
looks good

**Review by xStylistic — APPROVED** [review]

**Review by SazzGuy — APPROVED** [review]
very detailed layout nice

**Pull request merged**
