### PR TITLE
Logic for traversing through views (file -> difficulty -> first q&a rn) + refactored code

### PR DESCRIPTION
**Pull request by jerryq0101**
walk through of changes 

https://www.loom.com/share/8f452eb459d2476fa61594ef01d45f49

questions will probably not be on a new view is the gist I am getting @SazzGuy

### CODE REVIEW

**Review by bem-boi — APPROVED** [review]
nice pr jerry. i liek the video. easy to understand

**Review by ZekeWeng — APPROVED** [review]
Good call splitting the Interactor

**Review by xStylistic — APPROVED** [review]
great pr, good video rundown

**Review by SazzGuy — APPROVED** [review]
nice implementation

**Pull request merged**
