### PR TITLE
added easy, medium, hard, question views and question answer views

### PR DESCRIPTION
**Pull request by xStylistic**

### CODE REVIEW

**Review by SazzGuy — APPROVED** [review]
The different versions of the view for different difficulty levels works well. Current QuestionAnswerView is redundant btw

**Review by bem-boi — APPROVED** [review]
very good pr. nice gui.

**Review by jerryq0101 — APPROVED** [review]
aight

**Review by ZekeWeng — APPROVED** [review]
Lots of Code! Impressive. You must be so proficient in Swing + Java.

**Pull request merged**
